### PR TITLE
Add public key as attachment

### PR DESCRIPTION
**Pull request by meskio**

### CODE REVIEW

**Comment by elijh** [comment]
I wonder if there is anything we can do to make the filename be less english specific.

"email-encryption-key-for-user@domain.org" is good in english, but not so good otherwise.

**Comment by elijh** [comment]
maybe the file should have .asc file suffix. This is what enigmail does when it attaches your public key.

**Comment by elijh** [comment]
how about?: "user@domain.org-email-key.asc"

"email" is probably one word that scans in a lot of languages.

**Comment by kalikaneko** [comment]
> how about?: "user@domain.org-email-key.asc"
:+1:

**Comment by meskio** [comment]
Sounds good to me the new proposed name. Changed.

**Pull request merged**
